# Generated by Django 3.2.3 on 2021-06-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20210609_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeleteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_delete_request', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
