# Generated by Django 3.2.3 on 2021-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_userdeleterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
